# Generated by Django 4.1.3 on 2022-11-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_process_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='controll',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='organ',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
