# Generated by Django 4.1.3 on 2022-11-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_process_area_alter_process_controll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='distribution',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
