# Generated by Django 4.1.3 on 2022-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='distribution',
            field=models.DateField(auto_now_add=True),
        ),
    ]
