# Generated by Django 4.1.3 on 2022-11-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_alter_process_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='jugde',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
