# Generated by Django 4.1.3 on 2022-11-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_process_jugde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
