# Generated by Django 4.1.3 on 2022-11-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_alter_process_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='jugde',
        ),
    ]
