# Generated by Django 4.1.3 on 2022-11-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
        ('process', '0011_remove_process_jugde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='process',
            name='status',
        ),
        migrations.RemoveField(
            model_name='process',
            name='value',
        ),
        migrations.AddField(
            model_name='process',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.judge'),
        ),
    ]
