# Generated by Django 4.1.3 on 2022-11-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_process_slug_process_status_process_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='class_project',
            new_name='class_process',
        ),
    ]
