# Generated by Django 4.1.3 on 2022-11-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
        ('process', '0014_rename_class_project_process_class_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='judge.judge'),
            preserve_default=False,
        ),
    ]
