# Generated by Django 4.1.3 on 2023-01-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0015_alter_process_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='court',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
