# Generated by Django 4.1.3 on 2023-01-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0017_alter_process_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
