# Generated by Django 4.1.3 on 2023-01-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0018_alter_process_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='class_process',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
