# Generated by Django 4.1.3 on 2023-01-19 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_remove_judge_cnj'),
        ('process', '0019_alter_process_class_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='forum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.judge'),
        ),
    ]
