# Generated by Django 3.2.16 on 2023-01-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0023_alter_process_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='parts',
        ),
    ]
