# Generated by Django 3.2.16 on 2023-01-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_remove_part_parts'),
        ('process', '0024_remove_process_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='parts', to='parts.Part'),
        ),
    ]
