# Generated by Django 3.2.16 on 2023-01-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_remove_part_parts'),
        ('process', '0025_process_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='parts',
            field=models.ManyToManyField(blank=True, to='parts.Part'),
        ),
    ]
