# Generated by Django 3.2.16 on 2023-01-23 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_remove_judge_cnj'),
        ('process', '0029_alter_process_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='class_process',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='forum',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.judge'),
        ),
        migrations.AlterField(
            model_name='process',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
