# Generated by Django 3.2.16 on 2023-01-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0030_auto_20230122_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
