# Generated by Django 3.2.16 on 2023-01-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0031_alter_process_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='subject',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
