# Generated by Django 4.1.3 on 2022-11-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('R', 'RÉU'), ('J', 'JUIZ'), ('A', 'AUTOR')], max_length=1),
        ),
    ]
