# Generated by Django 4.1.3 on 2022-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='cpf',
            field=models.CharField(default='122', max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
