# Generated by Django 4.1.3 on 2022-11-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_part_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('Réu', 'RÉU'), ('Juiz', 'JUIZ'), ('Autor', 'AUTOR')], max_length=5),
        ),
    ]
