# Generated by Django 4.1.3 on 2022-11-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_process_jugde'),
        ('parts', '0003_alter_part_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='process',
            field=models.ManyToManyField(blank=True, null=True, related_name='parts', to='process.process'),
        ),
    ]
