# Generated by Django 4.1.3 on 2023-01-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_judge_cnj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='cnj',
        ),
    ]
