# Generated by Django 4.1.3 on 2022-11-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0013_process_slug_process_status_process_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.process')),
            ],
        ),
    ]
