# Generated by Django 4.1.3 on 2022-11-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_rename_class_project_process_class_process'),
        ('movement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='process.process'),
        ),
    ]
